name: Sync to Hugging Face hub
on:
  push:
    branches: [main]
  workflow_dispatch:
  
jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true

      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Ensure .gitattributes
        run: |
          if [ ! -f .gitattributes ]; then
            echo "hifi-gan/generator_v1.pt filter=lfs diff=lfs merge=lfs -text" > .gitattributes
            git add .gitattributes
            git commit -m "Add .gitattributes for LFS"
          fi

      - name: Fetch and checkout LFS objects
        run: |
          git lfs fetch --all
          git lfs checkout

      - name: Re-track model with LFS
        run: |
          git rm --cached hifi-gan/generator_v1.pt || true
          git add hifi-gan/generator_v1.pt
          git commit -m "Retrack generator_v1.pt via LFS" || echo "No changes to commit"

      - name: Push to hub
        env:
          H_TOKEN: ${{ secrets.H_TOKEN }}
        run: |
          git push --force https://unbre4kab1e:$H_TOKEN@huggingface.co/spaces/unbre4kab1e/TTS main
